config/routes.rb
Rails.application.routes.draw do

  root 'institutions#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :institutions do
    resources :employees, only: [:new, :create, :destroy]
    resources :suppliers, only: [:new, :create]
    resources :drugs, only: [:new, :create]
    resources :visit_notes, only: [:new, :create, :destroy]
  end

  resources :suppliers, only: [:index]
  resources :pharmacies, only: [:new, :create, :destroy]
  resources :laboratories, only: [:new, :create, :destroy]
  resources :medical_vendors, only: [:new, :create, :destroy]
  resources :radiologies, only: [:new, :create, :destroy]
  resources :clinics, only: [:new, :create, :destroy]
  resources :midwifes, only: [:new, :create, :destroy]
  resources :dentists, only: [:new, :create, :destroy]
  resources :drugs, only: [:destroy]

  get '/units/new' => 'units#new'

  scope 'users' do
      get '/relative' => 'relatives#search_relative'
    scope '/:id' do
      get '/set_photo' => 'users#set_photo'
      get '/set_profile_details' => 'users#set_profile_details'
      get '/set_medical_histories' => 'users#set_medical_histories'
      get '/set_relatives' => 'users#set_relatives'

      put '/set_profile_details' => 'users#update_profile_details'
      post '/relatives' => 'relatives#create'
      put '/sign_up_details' => 'users#sign_up_details'
      post '/upload_photo' => 'users#upload_photo'
      post '/add_allergies' => 'users#add_allergies'
    end
  end

  scope 'institutions' do
    scope ':institution_id' do
      scope 'visit_notes' do
        scope ':id' do
          get '/step_two' => 'visit_note_steps#step_two'
          get '/step_three' => 'visit_note_steps#step_three'
          get '/step_four' => 'visit_note_steps#step_four'
          get '/step_five' => 'visit_note_steps#step_five'
          get '/step_six' => 'visit_note_steps#step_six'

          post '/set_diagnosis' => 'visit_note_steps#set_diagnosis'
          post '/set_therapy' => 'visit_note_steps#set_therapy'
          post '/set_action' => 'visit_note_steps#set_action'
          post '/set_allergies' => 'visit_note_steps#set_allergies'
          post '/set_medical_treatment' => 'visit_note_steps#set_medical_treatment'
        end
      end
    end
  end

  scope 'hospitals' do
    scope ':id' do
      put '/inst_profile' => 'hospital_steps#add_inst_profile'
      put '/inst_details' => 'hospital_steps#add_inst_details'
      post '/beds' => 'hospital_beds#create'
      post '/departments' => 'departments#add_in_inst'
      post '/assign_supplier' => 'suppliers#assign'

      get '/step_two' => 'hospital_steps#step_two'
      get '/step_three' => 'hospital_steps#step_three'
      get '/step_four' => 'hospital_steps#step_four'

    end
  end


  resources :users
  resources :hospitals


end

app/models/institution.rb
class Institution < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :suppliers_institutions
  has_one :hospital
  has_many :billings
  has_many :institution_departments


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @institutions = current_user.institutions
  end

  def new
    @institution = Institution.new
  end

  def create
    institution = Institution.new(inst_params)
    if institution.save
      case params[:inst_type]
        when 'hospital'
          hospital_create(institution)
        when 'pharmacy'
          hospital_create(institution)
        else ''
          hospital_create(institution)
      end
    else
      respond_to do |format|
        format.html { redirect_to '/institutions/new', alert:  institution.errors.full_messages}
        format.json {
          render json: {:status => 1, :message => institution.errors.full_messages}, :status => 400
        }
      end
    end
  end

  def show
    @institution = get_institution(params[:id])
    @employees = @institution.users
  end

  def edit
    @institution = get_institution(params[:id])
  end

  def update
    @institution = get_institution(params[:id])
    if @institution.update(institution_params)
      redirect_to institution_path(@institution)
    else
      render 'edit'
    end
  end

  def destroy
    @institution = get_institution(params[:id])
    @institution.destroy
    redirect_to institutions_path
  end

  def hospital_create(institution)
    hospital = institution.build_hospital(hospitals_params)
    if hospital.save
      respond_to do |format|
        format.html { redirect_to "/hospitals/#{hospital.id}/step_two" }
        format.json {
          render json: {:status => 0, :message => 'success', :data => hospital}, :status => 200
        }
      end
    end
  end

  private

  def get_institution(id)
    current_user.institutions.find(id)
  end

  def institution_params
    params.require(:institution).permit(:name, :address_1, :address_2, :city, :state, :zip, :country)
  end

  def inst_params
    params.permit(:name, :admin_mr, :inst_type)
  end

  def hospitals_params
    params[:director_mr] = get_director
    params.permit(:number_code_rs, :type_of_hospital, :name, :hospital_class, :director_mr, :admin_mr, :organizer, :organizer_rs,
    :status, :date_started, :pentahapan, :accreditation_department, :accreditation_date, :determination, :license_number,
    :certificate_number, :sertificate_date, :certificate_by, :sifat, :validity_period, :motto, :mission, :visions)
  end

  def get_director
    if params[:director_mr].present?
      if User.where(:rm_number => params[:director_mr]).exists?
        return params[:director_mr]
      else
        nil
      end
    else
      nil
    end
  end

end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for @institution, html: { class: 'form-horizontal bordered-row' } do |f| %>
  <% if @institution.errors.any? %>
    <div class="alert alert-close alert-danger">
      <%= link_to '', '#', title: 'Close', class: 'glyph-icon alert-close-btn icon-remove' %>
      <div class="bg-red alert-icon">
        <i class="glyph-icon icon-times"></i>
      </div>
      <div class="alert-content">
        <h4 class="alert-title">Oops! The following errors occured:</h4>
        <ul>
          <% @institution.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_1, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :address_1, class: 'form-control', placeholder: 'Enter address 1' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_2, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :address_2, class: 'form-control', placeholder: 'Enter address 2' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :city, class: 'form-control', placeholder: 'Enter city' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :state, class: 'form-control', placeholder: 'Enter state' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :zip, class: 'form-control', placeholder: 'Enter zip' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: 'col-sm-3 control-label' %>
    <div class="col-sm-6">
      <%= country_select 'institution', 'country', {}, { class: 'form-control' } %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-3">
      <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/institutions/index.html.erb
<% content_for :title do %>
  <title>Welcome! Dashboard | Dokterku</title>
<% end %>

<div id="sb-site">

<div id="page-wrapper">
  <%= render 'partials/header' %>
  <%= render 'partials/user_sidebar' %>
    <div id="page-content-wrapper">
        <div id="page-content">

                <div class="container">

<div id="page-title">
  <h2>Institutions&nbsp;&nbsp;&nbsp;<%= link_to 'New Institution', new_institution_path, class: 'btn btn-primary btn-sm' %></h2>
<p>All institutions registered in your database are listed below.</p>
<div id="theme-options" class="admin-options">
<a href="javascript:void(0);" class="btn btn-primary theme-switcher tooltip-button" data-placement="left" title="Color schemes and layout options">
    <i class="glyph-icon icon-linecons-cog icon-spin"></i>
</a>
<div id="theme-switcher-wrapper">
    <div class="scroll-switcher">
        <h5 class="header">Layout options</h5>
        <ul class="reset-ul">
            <li>
                <label for="boxed-layout">Boxed layout</label>
                <input type="checkbox" data-toggletarget="boxed-layout" id="boxed-layout" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-header">Fixed header</label>
                <input type="checkbox" data-toggletarget="fixed-header" id="fixed-header" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-sidebar">Fixed sidebar</label>
                <input type="checkbox" data-toggletarget="fixed-sidebar" id="fixed-sidebar" class="input-switch-alt">
            </li>
            <li>
                <label for="closed-sidebar">Closed sidebar</label>
                <input type="checkbox" data-toggletarget="closed-sidebar" id="closed-sidebar" class="input-switch-alt">
            </li>
        </ul>
        <div class="boxed-bg-wrapper hide">
            <h5 class="header">
                Boxed Page Background
                <a class="set-background-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
            </h5>
            <div class="theme-color-wrapper clearfix">
                <h5>Patterns</h5>
                <a class="tooltip-button set-background-style pattern-bg-3" data-header-bg="pattern-bg-3" title="Pattern 3" href="javascript:void(0);">Pattern 3</a>
                <a class="tooltip-button set-background-style pattern-bg-4" data-header-bg="pattern-bg-4" title="Pattern 4" href="javascript:void(0);">Pattern 4</a>
                <a class="tooltip-button set-background-style pattern-bg-5" data-header-bg="pattern-bg-5" title="Pattern 5" href="javascript:void(0);">Pattern 5</a>
                <a class="tooltip-button set-background-style pattern-bg-6" data-header-bg="pattern-bg-6" title="Pattern 6" href="javascript:void(0);">Pattern 6</a>
                <a class="tooltip-button set-background-style pattern-bg-7" data-header-bg="pattern-bg-7" title="Pattern 7" href="javascript:void(0);">Pattern 7</a>
                <a class="tooltip-button set-background-style pattern-bg-8" data-header-bg="pattern-bg-8" title="Pattern 8" href="javascript:void(0);">Pattern 8</a>
                <a class="tooltip-button set-background-style pattern-bg-9" data-header-bg="pattern-bg-9" title="Pattern 9" href="javascript:void(0);">Pattern 9</a>
                <a class="tooltip-button set-background-style pattern-bg-10" data-header-bg="pattern-bg-10" title="Pattern 10" href="javascript:void(0);">Pattern 10</a>

                <div class="clear"></div>

                <h5 class="mrg15T">Solids &amp;Images</h5>
                <a class="tooltip-button set-background-style bg-black" data-header-bg="bg-black" title="Black" href="javascript:void(0);">Black</a>
                <a class="tooltip-button set-background-style bg-gray mrg10R" data-header-bg="bg-gray" title="Gray" href="javascript:void(0);">Gray</a>

                <a class="tooltip-button set-background-style full-bg-1" data-header-bg="full-bg-1 fixed-bg" title="Image 1" href="javascript:void(0);">Image 1</a>
                <a class="tooltip-button set-background-style full-bg-2" data-header-bg="full-bg-2 fixed-bg" title="Image 2" href="javascript:void(0);">Image 2</a>
                <a class="tooltip-button set-background-style full-bg-3" data-header-bg="full-bg-3 fixed-bg" title="Image 3" href="javascript:void(0);">Image 3</a>
                <a class="tooltip-button set-background-style full-bg-4" data-header-bg="full-bg-4 fixed-bg" title="Image 4" href="javascript:void(0);">Image 4</a>
                <a class="tooltip-button set-background-style full-bg-5" data-header-bg="full-bg-5 fixed-bg" title="Image 5" href="javascript:void(0);">Image 5</a>
                <a class="tooltip-button set-background-style full-bg-6" data-header-bg="full-bg-6 fixed-bg" title="Image 6" href="javascript:void(0);">Image 6</a>

            </div>
        </div>
        <h5 class="header">
            Header Style
            <a class="set-adminheader-style" data-header-bg="bg-gradient-9" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-adminheader-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-adminheader-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-adminheader-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-adminheader-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-adminheader-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-adminheader-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-adminheader-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-adminheader-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
        <h5 class="header">
            Sidebar Style
            <a class="set-sidebar-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-sidebar-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-sidebar-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-sidebar-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-sidebar-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-sidebar-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-sidebar-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-sidebar-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-sidebar-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
    </div>
</div>
</div>
</div>

<div class="row">
<div class="col-xs-12 table-responsive">
  <% if @institutions.any? %>
    <table class="table table-stripped" id="hospital_table">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @institutions.each do |institution| %>
          <tr>
            <td>
              <div class="content-box-wrapper">
                <div class="row">
                  <div class="col-xs-6">
                    <h3 class="institution-title"><%= link_to truncate(institution.name), institution_path(institution) %></h3>
                  </div>
                  <div class="col-xs-6 text-right">
                    <%= link_to edit_institution_path(institution), class: 'btn btn-sm btn-info tooltip-button', data: { placement: 'top' }, title: 'Edit details' do %>
                        <i class="glyph-icon icon-pencil"></i>
                    <% end %>&nbsp;&nbsp;
                    <%= link_to institution_path(institution), method: :delete, class: 'btn btn-sm btn-danger tooltip-button', data: { placement: 'top', confirm: 'Are you sure?', title: 'Delete' } do %>
                        <i class="glyph-icon icon-trash"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info">You don't have any institutions right now.</div>
  <% end %>
</div>
</div>
</div>
                </div>



        </div>
    </div>
</div>

app/views/institutions/show.html.erb
<% content_for :title do %>
  <title>Institution Details | Dashboard | Dokterku</title>
<% end %>

<div id="sb-site">
  <div id="page-wrapper">
      <%= render 'partials/header' %>
      <%= render 'partials/user_sidebar' %>
          <div id="page-content-wrapper">
              <div id="page-content">
                  <div class="container">
                  <% if @institution.verification_number.present? && @institution.admin_mr == current_user.rm_number%>
                        <div id="page-title">
                            <h2>Institution Details&nbsp;&nbsp;<%= link_to 'Edit', edit_institution_path(@institution), class: 'btn btn-primary' %>&nbsp;&nbsp;<%= link_to 'Delete', institution_path(@institution), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></h2>
                            <p>See all information about this institution.</p>
                            <div id="theme-options" class="admin-options">
                                <a href="javascript:void(0);" class="btn btn-primary theme-switcher tooltip-button" data-placement="left" title="Color schemes and layout options">
                                    <i class="glyph-icon icon-linecons-cog icon-spin"></i>
                                </a>
                                <div id="theme-switcher-wrapper">
                                    <div class="scroll-switcher">
                                        <h5 class="header">Layout options</h5>
                                        <ul class="reset-ul">
                                            <li>
                                                <label for="boxed-layout">Boxed layout</label>
                                                <input type="checkbox" data-toggletarget="boxed-layout" id="boxed-layout" class="input-switch-alt">
                                            </li>
                                            <li>
                                                <label for="fixed-header">Fixed header</label>
                                                <input type="checkbox" data-toggletarget="fixed-header" id="fixed-header" class="input-switch-alt">
                                            </li>
                                            <li>
                                                <label for="fixed-sidebar">Fixed sidebar</label>
                                                <input type="checkbox" data-toggletarget="fixed-sidebar" id="fixed-sidebar" class="input-switch-alt">
                                            </li>
                                            <li>
                                                <label for="closed-sidebar">Closed sidebar</label>
                                                <input type="checkbox" data-toggletarget="closed-sidebar" id="closed-sidebar" class="input-switch-alt">
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="content-box">
                                    <h3 class="content-box-header bg-primary">Institution Details</h3>
                                    <div class="content-box-wrapper">
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <h2><%= @institution.name %></h2>
                                                <br>
                                                <div class="row">
                                                    <div class="col-xs-1">
                                                        <h4 class="glyphicon glyphicon-map-marker"></h4>
                                                    </div>
                                                    <div class="col-xs-10">
                                                        <h4><%= @institution.address_1 %></h4>
                                                        <h4><%= @institution.address_2 %></h4>
                                                        <h4><%= @institution.city %> <%= @institution.zip %></h4>
                                                        <h4><%= @institution.state %>, <%= @institution.country_name %></h4>
                                                        <br>
                                                    </div>
                                                    <div class="col-xs-12">
                                                        <br>
                                                        <% if @employees.any? %>
                                                            <table class="table table-stripped" id="hospital_table">
                                                                <thead>
                                                                    <tr>
                                                                        <th>RM Number</th>
                                                                        <th>Full Name</th>
                                                                        <th>Email</th>
                                                                        <th>Actions</td>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <% @employees.each do |employee| %>
                                                                        <tr>
                                                                            <td><%= employee.rm_number %></td>
                                                                            <td><%= employee.full_name %></td>
                                                                            <td><%= employee.email %></td>
                                                                            <td>
                                                                                <%= link_to 'Details', user_path(employee), class: 'btn btn-info' %>
                                                                                <%= link_to 'Delete', institution_employee_path(@institution, employee), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
                                                                            </td>
                                                                        </tr>
                                                                    <% end %>
                                                                </tbody>
                                                            </table>
                                                            <br>
                                                            <%= link_to 'Add Employee', new_institution_employee_path(@institution), class: 'btn btn-block btn-primary' %>
                                                        <% else %>
                                                            <div class="alert alert-info">You don't have any admins right now.</div>
                                                        <% end %>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                  <% else %>
                        <div class="container">
                          <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
                              <h2 class="mrg10A">Institution Details</h2>
                              <p class="ml-10 h5 mt-20">To continue working, we need to verify that you are the authorize person who is in charge of this institution.</p>
                              <p class="mt-10 ml-10 h5">Please enter your verification number</p>
                            </div>
                          </div>
                          <div class="row pl-60 mt-30">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
                              <div>
                                                  <span class="h5">
                                                      <strong>Your MR#</strong>
                                                  </span>
                                <span class="ml-10 h5 ml-35"><%= current_user.rm_number %></span>
                              </div>
                            </div>
                          </div>
                          <div class="row pl-60 mt-30">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
                              <form action="" id="inst-verify-number">
                                <div class="form-group">
                                  <label class="col-sm-2 control-label h5 p-0"><strong>Verification number</strong></label>
                                  <div class="col-sm-5 p-0">
                                    <input type="text" name="verf_no" id="verf_no" class="form-control" placeholder="Enter number">
                                  </div>
                                </div>
                              </form>
                            </div>
                          </div>
                          <div class="row pl-60">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
                              <div class="mt-20">
                                <button class="btn ra-100 btn-primary btn-sm">Next</button>
                              </div>
                            </div>
                          </div>
                        </div>
                  <% end %>

              </div>
          </div>
        </div>
    </div>
</div>