config/routes.rb
Rails.application.routes.draw do

  root 'institutions#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :institutions do
    resources :employees, only: [:new, :create, :destroy]
    resources :suppliers, only: [:new, :create]
    resources :drugs, only: [:new, :create]
    resources :visit_notes, only: [:new, :create, :destroy]
  end

  resources :suppliers, only: [:index]
  resources :pharmacies, only: [:new, :create, :destroy]
  resources :laboratories, only: [:new, :create, :destroy]
  resources :medical_vendors, only: [:new, :create, :destroy]
  resources :radiologies, only: [:new, :create, :destroy]
  resources :clinics, only: [:new, :create, :destroy]
  resources :midwifes, only: [:new, :create, :destroy]
  resources :dentists, only: [:new, :create, :destroy]
  resources :drugs, only: [:destroy]

  get '/units/new' => 'units#new'

  scope 'users' do
      get '/relative' => 'relatives#search_relative'
    scope '/:id' do
      get '/set_photo' => 'users#set_photo'
      get '/set_profile_details' => 'users#set_profile_details'
      get '/set_medical_histories' => 'users#set_medical_histories'
      get '/set_relatives' => 'users#set_relatives'

      put '/set_profile_details' => 'users#update_profile_details'
      post '/relatives' => 'relatives#create'
      put '/sign_up_details' => 'users#sign_up_details'
      post '/upload_photo' => 'users#upload_photo'
      post '/add_allergies' => 'users#add_allergies'
    end
  end

  scope 'institutions' do
    scope ':institution_id' do
      scope 'visit_notes' do
        scope ':id' do
          get '/step_two' => 'visit_note_steps#step_two'
          get '/step_three' => 'visit_note_steps#step_three'
          get '/step_four' => 'visit_note_steps#step_four'
          get '/step_five' => 'visit_note_steps#step_five'
          get '/step_six' => 'visit_note_steps#step_six'

          post '/set_diagnosis' => 'visit_note_steps#set_diagnosis'
          post '/set_therapy' => 'visit_note_steps#set_therapy'
          post '/set_action' => 'visit_note_steps#set_action'
          post '/set_allergies' => 'visit_note_steps#set_allergies'
          post '/set_medical_treatment' => 'visit_note_steps#set_medical_treatment'
        end
      end
    end
  end

  scope 'hospitals' do
    scope ':id' do
      put '/inst_profile' => 'hospital_steps#add_inst_profile'
      put '/inst_details' => 'hospital_steps#add_inst_details'
      post '/beds' => 'hospital_beds#create'
      post '/departments' => 'departments#add_in_inst'
      post '/assign_supplier' => 'suppliers#assign'

      get '/step_two' => 'hospital_steps#step_two'
      get '/step_three' => 'hospital_steps#step_three'
      get '/step_four' => 'hospital_steps#step_four'

    end
  end


  resources :users
  resources :hospitals


end

app/models/bed.rb
class Bed < ActiveRecord::Base


  after_initialize :set_values, :if => :new_record?


  private

    def set_values
      self.vvip_free = self.vvip
      self.vip_free = self.vip
      self.i_free = self.i
      self.ii_free = self.ii
      self.iii_free = self.iii
      self.ruang_isolasi_free = self.ruang_isolasi
      self.igd_free = self.igd
      self.vk_free = self.vk
      self.ok_free = self.ok
      self.perinatologi_free = self.perinatologi
    end




end

app/models/billing.rb
class Billing < ActiveRecord::Base
  belongs_to :user
  belongs_to :institution
  belongs_to :visit_note
  has_many :payments
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_and_belongs_to_many :hospitals
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user
  has_many :prescriptions
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :prescriptions
  belongs_to :pharmacy
  has_many :inventories
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

  belongs_to :institution
  has_many :hospitals_departments
  has_many :visit_notes
  has_one :bed

  validates :name, presence: true

  def country_name
    c = ISO3166::Country[country]
    c.name || c.translations[I18n.locale.to_s]
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :suppliers_institutions
  has_one :hospital
  has_many :billings
  has_many :institution_departments


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :pharmacy
  belongs_to :drug
end

app/models/login.rb
class Login < ActiveRecord::Base
  belongs_to :user
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
  belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :billing
end

app/models/relative.rb
class Relative < ActiveRecord::Base

  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base

  has_many :drugs
  has_many :suppliers_institutions


  after_initialize :set_values, if: :new_record?

  def set_values
    self.supplier_code ||= generate_supplier_code
  end

  def generate_supplier_code
    code = loop do
      l = ('A'..'Z').to_a
      l.delete('I')
      l.delete('O')
      l.delete('L')
      lt = l.shuffle[0..0].join
      n = (0..9).to_a.shuffle[0..2].join
      code = lt + n
      break code unless Supplier.exists?(supplier_code: code)
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :validatable

  after_initialize :generate_rm_number, if: :new_record?
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :institutions
  has_many :user_histories
  has_many :logins
  has_many :user_photos
  has_many :visit_notes
  has_many :prescriptions
  has_many :billings
  has_many :user_allergies
  has_many :relatives
  has_many :institutions, foreign_key: 'admin_mr', primary_key: 'rm_number'
  has_many :pharmacies, :foreign_key => :admin_mr, :primary_key => :rm_number

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def full_name
    return "#{self.salutation} #{self.first_name} #{self.middle_name} #{self.last_name}"
  end

  def active_for_authentication?
    super and !self.disabled
  end

  def generate_rm_number
    self.rm_number = loop do
      l = ('A'..'Z').to_a
      l.delete('I')
      l.delete('O')
      l.delete('L')
      lt = l.shuffle[0..2].join
      n = (0..9).to_a.shuffle[0..3].join
      rm = lt + n
      break rm unless User.exists?(rm_number: rm)
    end
  end


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end

  def admin_mr?(inst_id)
    if Institution.where(:id => inst_id, :admin_mr => self.rm_number).exists?
      true
    else
      false
    end
  end

  def get_hospitals
    data = Institution.includes(:hospital).where(:admin_mr => self.rm_number, :inst_type => 'hospital').order(:name => :asc)
    data = data.as_json(:include => :hospital)
  end

end

app/models/user_photo.rb
class UserPhoto < ActiveRecord::Base
  belongs_to :user
end

app/models/visit_icu.rb
class VisitIcu < ActiveRecord::Base
end

app/models/visit_note.rb
class VisitNote < ActiveRecord::Base
  belongs_to :user
  has_many :visit_actions
  has_many :billings
  has_one :visit_diagnostic
  has_many :visit_therapies
  has_many :visit_allergy_histories
  has_many :visit_medicines

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    @user = User.find_by(rm_number: params[:rm_number])
    @institution = get_institution(params[:institution_id])
    if @user
      @institution.users << @user
    else
      flash[:alert] = 'We couldn\'t find a user with the specified RM number.'
    end
    redirect_to @institution
  end

  def destroy
    @institution = get_institution(params[:institution_id])
    @user = @institution.users.find(params[:id])
    @institution.users.delete(@user)
    redirect_to institutions_path
  end

  private

  def get_institution(id)
    current_user.institutions.find(id)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/new.html.erb
<% content_for :title do %>
  <title>Add New Employee | Dashboard | Dokterku</title>
<% end %>

<div id="sb-site">

<div id="page-wrapper">
<%= render 'partials/header' %>
<%= render 'partials/sidebar' %>
    <div id="page-content-wrapper">
        <div id="page-content">

                <div class="container">

<div id="page-title">
<h2>Add New Employee</h2>
<p>Fill in the form below with appropriate information and click "Save".</p>
<div id="theme-options" class="admin-options">
<a href="javascript:void(0);" class="btn btn-primary theme-switcher tooltip-button" data-placement="left" title="Color schemes and layout options">
    <i class="glyph-icon icon-linecons-cog icon-spin"></i>
</a>
<div id="theme-switcher-wrapper">
    <div class="scroll-switcher">
        <h5 class="header">Layout options</h5>
        <ul class="reset-ul">
            <li>
                <label for="boxed-layout">Boxed layout</label>
                <input type="checkbox" data-toggletarget="boxed-layout" id="boxed-layout" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-header">Fixed header</label>
                <input type="checkbox" data-toggletarget="fixed-header" id="fixed-header" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-sidebar">Fixed sidebar</label>
                <input type="checkbox" data-toggletarget="fixed-sidebar" id="fixed-sidebar" class="input-switch-alt">
            </li>
            <li>
                <label for="closed-sidebar">Closed sidebar</label>
                <input type="checkbox" data-toggletarget="closed-sidebar" id="closed-sidebar" class="input-switch-alt">
            </li>
        </ul>
        <div class="boxed-bg-wrapper hide">
            <h5 class="header">
                Boxed Page Background
                <a class="set-background-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
            </h5>
            <div class="theme-color-wrapper clearfix">
                <h5>Patterns</h5>
                <a class="tooltip-button set-background-style pattern-bg-3" data-header-bg="pattern-bg-3" title="Pattern 3" href="javascript:void(0);">Pattern 3</a>
                <a class="tooltip-button set-background-style pattern-bg-4" data-header-bg="pattern-bg-4" title="Pattern 4" href="javascript:void(0);">Pattern 4</a>
                <a class="tooltip-button set-background-style pattern-bg-5" data-header-bg="pattern-bg-5" title="Pattern 5" href="javascript:void(0);">Pattern 5</a>
                <a class="tooltip-button set-background-style pattern-bg-6" data-header-bg="pattern-bg-6" title="Pattern 6" href="javascript:void(0);">Pattern 6</a>
                <a class="tooltip-button set-background-style pattern-bg-7" data-header-bg="pattern-bg-7" title="Pattern 7" href="javascript:void(0);">Pattern 7</a>
                <a class="tooltip-button set-background-style pattern-bg-8" data-header-bg="pattern-bg-8" title="Pattern 8" href="javascript:void(0);">Pattern 8</a>
                <a class="tooltip-button set-background-style pattern-bg-9" data-header-bg="pattern-bg-9" title="Pattern 9" href="javascript:void(0);">Pattern 9</a>
                <a class="tooltip-button set-background-style pattern-bg-10" data-header-bg="pattern-bg-10" title="Pattern 10" href="javascript:void(0);">Pattern 10</a>

                <div class="clear"></div>

                <h5 class="mrg15T">Solids &amp;Images</h5>
                <a class="tooltip-button set-background-style bg-black" data-header-bg="bg-black" title="Black" href="javascript:void(0);">Black</a>
                <a class="tooltip-button set-background-style bg-gray mrg10R" data-header-bg="bg-gray" title="Gray" href="javascript:void(0);">Gray</a>

                <a class="tooltip-button set-background-style full-bg-1" data-header-bg="full-bg-1 fixed-bg" title="Image 1" href="javascript:void(0);">Image 1</a>
                <a class="tooltip-button set-background-style full-bg-2" data-header-bg="full-bg-2 fixed-bg" title="Image 2" href="javascript:void(0);">Image 2</a>
                <a class="tooltip-button set-background-style full-bg-3" data-header-bg="full-bg-3 fixed-bg" title="Image 3" href="javascript:void(0);">Image 3</a>
                <a class="tooltip-button set-background-style full-bg-4" data-header-bg="full-bg-4 fixed-bg" title="Image 4" href="javascript:void(0);">Image 4</a>
                <a class="tooltip-button set-background-style full-bg-5" data-header-bg="full-bg-5 fixed-bg" title="Image 5" href="javascript:void(0);">Image 5</a>
                <a class="tooltip-button set-background-style full-bg-6" data-header-bg="full-bg-6 fixed-bg" title="Image 6" href="javascript:void(0);">Image 6</a>

            </div>
        </div>
        <h5 class="header">
            Header Style
            <a class="set-adminheader-style" data-header-bg="bg-gradient-9" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-adminheader-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-adminheader-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-adminheader-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-adminheader-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-adminheader-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-adminheader-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-adminheader-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-adminheader-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
        <h5 class="header">
            Sidebar Style
            <a class="set-sidebar-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-sidebar-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-sidebar-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-sidebar-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-sidebar-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-sidebar-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-sidebar-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-sidebar-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-sidebar-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
    </div>
</div>
</div>
</div>

<div class="panel">
  <div class="panel-body">
    <%= form_tag institution_employees_path, class: 'form-horizontal bordered-row' do |f| %>
      <div class="form-group">
        <%= label_tag :rm_number, 'RM Number', class: 'col-sm-3 control-label' %>
        <div class="col-sm-6">
          <%= text_field_tag :rm_number, '', class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3">
          <%= submit_tag 'Save', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
          </div>
        </div>
    </div>
</div>