config/routes.rb
Rails.application.routes.draw do

  root 'institutions#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :institutions do
    resources :employees, only: [:new, :create, :destroy]
    resources :suppliers, only: [:new, :create]
    resources :drugs, only: [:new, :create]
    resources :visit_notes, only: [:new, :create, :destroy]
  end

  resources :suppliers, only: [:index]
  resources :pharmacies, only: [:new, :create, :destroy]
  resources :laboratories, only: [:new, :create, :destroy]
  resources :medical_vendors, only: [:new, :create, :destroy]
  resources :radiologies, only: [:new, :create, :destroy]
  resources :clinics, only: [:new, :create, :destroy]
  resources :midwifes, only: [:new, :create, :destroy]
  resources :dentists, only: [:new, :create, :destroy]
  resources :drugs, only: [:destroy]

  get '/units/new' => 'units#new'

  scope 'users' do
      get '/relative' => 'relatives#search_relative'
    scope '/:id' do
      get '/set_photo' => 'users#set_photo'
      get '/set_profile_details' => 'users#set_profile_details'
      get '/set_medical_histories' => 'users#set_medical_histories'
      get '/set_relatives' => 'users#set_relatives'

      put '/set_profile_details' => 'users#update_profile_details'
      post '/relatives' => 'relatives#create'
      put '/sign_up_details' => 'users#sign_up_details'
      post '/upload_photo' => 'users#upload_photo'
      post '/add_allergies' => 'users#add_allergies'
    end
  end

  scope 'institutions' do
    scope ':institution_id' do
      scope 'visit_notes' do
        scope ':id' do
          get '/step_two' => 'visit_note_steps#step_two'
          get '/step_three' => 'visit_note_steps#step_three'
          get '/step_four' => 'visit_note_steps#step_four'
          get '/step_five' => 'visit_note_steps#step_five'
          get '/step_six' => 'visit_note_steps#step_six'

          post '/set_diagnosis' => 'visit_note_steps#set_diagnosis'
          post '/set_therapy' => 'visit_note_steps#set_therapy'
          post '/set_action' => 'visit_note_steps#set_action'
          post '/set_allergies' => 'visit_note_steps#set_allergies'
          post '/set_medical_treatment' => 'visit_note_steps#set_medical_treatment'
        end
      end
    end
  end

  scope 'hospitals' do
    scope ':id' do
      put '/inst_profile' => 'hospital_steps#add_inst_profile'
      put '/inst_details' => 'hospital_steps#add_inst_details'
      post '/beds' => 'hospital_beds#create'
      post '/departments' => 'departments#add_in_inst'
      post '/assign_supplier' => 'suppliers#assign'

      get '/step_two' => 'hospital_steps#step_two'
      get '/step_three' => 'hospital_steps#step_three'
      get '/step_four' => 'hospital_steps#step_four'

    end
  end


  resources :users
  resources :hospitals


end

app/models/bed.rb
class Bed < ActiveRecord::Base


  after_initialize :set_values, :if => :new_record?


  private

    def set_values
      self.vvip_free = self.vvip
      self.vip_free = self.vip
      self.i_free = self.i
      self.ii_free = self.ii
      self.iii_free = self.iii
      self.ruang_isolasi_free = self.ruang_isolasi
      self.igd_free = self.igd
      self.vk_free = self.vk
      self.ok_free = self.ok
      self.perinatologi_free = self.perinatologi
    end




end

app/models/billing.rb
class Billing < ActiveRecord::Base
  belongs_to :user
  belongs_to :institution
  belongs_to :visit_note
  has_many :payments
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_and_belongs_to_many :hospitals
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user
  has_many :prescriptions
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :prescriptions
  belongs_to :pharmacy
  has_many :inventories
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

  belongs_to :institution
  has_many :hospitals_departments
  has_many :visit_notes
  has_one :bed

  validates :name, presence: true

  def country_name
    c = ISO3166::Country[country]
    c.name || c.translations[I18n.locale.to_s]
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :suppliers_institutions
  has_one :hospital
  has_many :billings
  has_many :institution_departments


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :pharmacy
  belongs_to :drug
end

app/models/login.rb
class Login < ActiveRecord::Base
  belongs_to :user
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
  belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :billing
end

app/models/relative.rb
class Relative < ActiveRecord::Base

  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base

  has_many :drugs
  has_many :suppliers_institutions


  after_initialize :set_values, if: :new_record?

  def set_values
    self.supplier_code ||= generate_supplier_code
  end

  def generate_supplier_code
    code = loop do
      l = ('A'..'Z').to_a
      l.delete('I')
      l.delete('O')
      l.delete('L')
      lt = l.shuffle[0..0].join
      n = (0..9).to_a.shuffle[0..2].join
      code = lt + n
      break code unless Supplier.exists?(supplier_code: code)
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :validatable

  after_initialize :generate_rm_number, if: :new_record?
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :institutions
  has_many :user_histories
  has_many :logins
  has_many :user_photos
  has_many :visit_notes
  has_many :prescriptions
  has_many :billings
  has_many :user_allergies
  has_many :relatives
  has_many :institutions, foreign_key: 'admin_mr', primary_key: 'rm_number'
  has_many :pharmacies, :foreign_key => :admin_mr, :primary_key => :rm_number

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def full_name
    return "#{self.salutation} #{self.first_name} #{self.middle_name} #{self.last_name}"
  end

  def active_for_authentication?
    super and !self.disabled
  end

  def generate_rm_number
    self.rm_number = loop do
      l = ('A'..'Z').to_a
      l.delete('I')
      l.delete('O')
      l.delete('L')
      lt = l.shuffle[0..2].join
      n = (0..9).to_a.shuffle[0..3].join
      rm = lt + n
      break rm unless User.exists?(rm_number: rm)
    end
  end


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end

  def admin_mr?(inst_id)
    if Institution.where(:id => inst_id, :admin_mr => self.rm_number).exists?
      true
    else
      false
    end
  end

  def get_hospitals
    data = Institution.includes(:hospital).where(:admin_mr => self.rm_number, :inst_type => 'hospital').order(:name => :asc)
    data = data.as_json(:include => :hospital)
  end

end

app/models/user_photo.rb
class UserPhoto < ActiveRecord::Base
  belongs_to :user
end

app/models/visit_icu.rb
class VisitIcu < ActiveRecord::Base
end

app/models/visit_note.rb
class VisitNote < ActiveRecord::Base
  belongs_to :user
  has_many :visit_actions
  has_many :billings
  has_one :visit_diagnostic
  has_many :visit_therapies
  has_many :visit_allergy_histories
  has_many :visit_medicines

end

app/views/partials/_header.html.erb
<div id="page-header" class="bg-gradient-9">
<div id="mobile-navigation">
<button id="nav-toggle" class="collapsed" data-toggle="collapse" data-target="#page-sidebar"><span></span></button>
<a href="/" class="logo-content-small" title="MonarchUI"></a>
</div>
<div id="header-logo" class="logo-bg">
<a href="/" class="logo-content-big" title="MonarchUI">
    Monarch <i>UI</i>
    <span>The perfect solution for user interfaces</span>
</a>
<a href="/" class="logo-content-small" title="MonarchUI">
    Monarch <i>UI</i>
    <span>The perfect solution for user interfaces</span>
</a>
<a id="close-sidebar" href="#" title="Close sidebar">
    <i class="glyph-icon icon-angle-left"></i>
</a>
</div>
<div id="header-nav-left">
<div class="user-account-btn dropdown">
    <a title="My Account" class="user-profile clearfix" data-toggle="dropdown">
      <img width="28" src="<%= gravatar_image_url current_user.email %>" alt="<%= current_user.full_name %>">
        <span><%= current_user.full_name %></span>
    </a>
</div>
</div><!-- #header-nav-left -->

<div id="header-nav-right">
  <% if not @current_web_admin %>
    <%= link_to edit_user_registration_path, class: 'header-btn tooltip-button', id: 'logout-btn', data: { placement: 'bottom' }, title: 'Edit Profile' do %>
      <i class="glyph-icon icon-user"></i>
    <% end %>
  <% end %>
  <%= link_to destroy_user_session_path, method: :delete, class: 'header-btn tooltip-button', id: 'logout-btn', data: { placement: 'bottom' }, title: 'Logout' do %>
    <i class="glyph-icon icon-power-off"></i>
  <% end %>
  &nbsp;&nbsp;
  <%= link_to edit_user_path({id: current_user.id}), class: 'btn btn-primary tooltip-button', id: 'logout-btn', data: { placement: 'bottom' }, title: current_user.rm_number do %>
    RM Number: <%= current_user.rm_number %>
  <% end %>
</div><!-- #header-nav-right -->

</div>

app/views/partials/_sidebar.html.erb
<div id="page-sidebar">
  <div class="scroll-sidebar">
    <ul id="sidebar-menu">
      <li class="header"><span>Overview</span></li>
        <li>
        <%= link_to users_path do %>
            <i class="glyph-icon icon-user"></i>
            <span>Users</span>
        <% end %>
        </li>
        <li>
        <%= link_to institutions_path do %>
            <i class="glyph-icon icon-medkit"></i>
            <span>Institutions</span>
        <% end %>
        </li>
    </ul>
  </div>
</div>

app/views/partials/_user_sidebar.html.erb
<div id="page-sidebar">
  <div class="scroll-sidebar">
    <ul id="sidebar-menu">

      <!-- user's block start -->

      <li class="header"><span>User</span></li>
      <li class="no-menu">
        <%= link_to user_path({id: current_user.id}) do %>
            <i class="glyph-icon icon-user"></i>
            <span>Profile dashboard</span>
        <% end %>
      </li>

      <!-- user's block end -->



      <li class="mt-20">
        <div style="display:inline-block" class="ptb-10">
          <%= link_to 'Create unit', new_institution_path, class: 'btn btn-border btn-alt border-primary font-primary btn-sm' %>
        </div>
      </li>
      <!-- -institution block start -->
      <% if current_user.get_hospitals.length > 0 %>
        <li class="header"><span>Hospitals</span></li>
        <% current_user.get_hospitals.each do |i|%>
          <% if i['hospital'].present? %>
            <li class="header mt-10">
              <span><%= i['hospital']['name'] %></span>
              <div class="sidebar-submenu-custome">
                <ul>
                  <li>
                    <%= link_to 'Dashboard', institution_path({id: i['hospital']['institution_id']})%>
                  </li>
                  <li>
                    <%= link_to 'Patient submission', '#'%>
                  </li>
                  <li>
                    <%= link_to 'Active patients', '#'%>
                  </li>
                  <li>
                    <%= link_to 'Departments', '#'%>
                  </li>
                  <li>
                    <%= link_to 'Analitics', '#'%>
                  </li>
                </ul>
              </div>
            </li>
          <% end %>
        <% end %>
      <% end %>

      <!-- institution block end -->
      <!-- pharmacy block start -->

      <% if current_user.institutions.where(:inst_type => 'pharmacy').length > 0%>
        <li class="header"><span>Pharmacies</span></li>
          <% current_user.institutions.where(:inst_type => 'pharmacy').order(:name => :asc).each do |pharm|%>
            <li class="header mt-10">
              <span><%= pharm.name %></span>
              <div class="sidebar-submenu-custome">
                <ul>
                  <li>
                    <%= link_to 'Dashboard', ''%>
                  </li>
                  <li>
                    <%= link_to 'Add supplier', new_institution_supplier_path({institution_id: pharm.id})%>
                  </li>
                  <li>
                    <%= link_to 'Add medicine', new_institution_drug_path({institution_id: pharm.id})%>
                  </li>
                </ul>
              </div>
            </li>
          <% end %>
      <% end %>

      <!-- pharmacy block end -->
      <!-- laboratory block start -->

      <% if current_user.institutions.where(:inst_type => 'laboratory').length > 0%>
        <li class="header"><span>Laboratories</span></li>
        <% current_user.institutions.where(:inst_type => 'laboratory').order(:name => :asc).each do |lab|%>
          <li class="header mt-10">
            <span><%= lab.name %></span>
            <div class="sidebar-submenu-custome">
              <ul>
                <li>
                  <%= link_to 'Dashboard', ''%>
                </li>
              </ul>
            </div>
          </li>
        <% end %>
      <% end %>
      <!-- laboratory block end -->

      <!-- Medical vendor block start -->

      <% if current_user.institutions.where(:inst_type => 'medical vendor').length > 0%>
          <li class="header"><span>Medical vendors</span></li>
          <% current_user.institutions.where(:inst_type => 'medical vendor').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Medical vendor block end -->
      <!-- Radiology block start -->

      <% if current_user.institutions.where(:inst_type => 'radiology').length > 0%>
          <li class="header"><span>Radiologies</span></li>
          <% current_user.institutions.where(:inst_type => 'radiology').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Radiology block end -->
      <!-- Clinic start -->

      <% if current_user.institutions.where(:inst_type => 'clinic').length > 0%>
          <li class="header"><span>Clinics</span></li>
          <% current_user.institutions.where(:inst_type => 'clinic').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Clinic block end -->
      <!-- Midwife block start -->

      <% if current_user.institutions.where(:inst_type => 'midwife').length > 0%>
          <li class="header"><span>Midwifes</span></li>
          <% current_user.institutions.where(:inst_type => 'midwife').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Midwife block end -->
      <!-- Dentist block start -->

      <% if current_user.institutions.where(:inst_type => 'dentist').length > 0%>
          <li class="header"><span>Dentists</span></li>
          <% current_user.institutions.where(:inst_type => 'dentist').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Dentist block end -->
      <!-- Other block start -->

      <% if current_user.institutions.where(:inst_type => 'other').length > 0%>
          <li class="header"><span>Other</span></li>
          <% current_user.institutions.where(:inst_type => 'other').order(:name => :asc).each do |lab|%>
              <li class="header mt-10">
                <span><%= lab.name %></span>
                <div class="sidebar-submenu-custome">
                  <ul>
                    <li>
                      <%= link_to 'Dashboard', ''%>
                    </li>
                  </ul>
                </div>
              </li>
          <% end %>
      <% end %>

      <!-- Other block end -->

      <li class="header">
        <div>
          <%= link_to users_path do %>
              <span><strong style="color:black">Users</strong></span>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>