config/routes.rb
Rails.application.routes.draw do

  root 'institutions#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :institutions do
    resources :employees, only: [:new, :create, :destroy]
    resources :suppliers, only: [:new, :create]
    resources :drugs, only: [:new, :create]
    resources :visit_notes, only: [:new, :create, :destroy]
  end

  resources :suppliers, only: [:index]
  resources :pharmacies, only: [:new, :create, :destroy]
  resources :laboratories, only: [:new, :create, :destroy]
  resources :medical_vendors, only: [:new, :create, :destroy]
  resources :radiologies, only: [:new, :create, :destroy]
  resources :clinics, only: [:new, :create, :destroy]
  resources :midwifes, only: [:new, :create, :destroy]
  resources :dentists, only: [:new, :create, :destroy]
  resources :drugs, only: [:destroy]

  get '/units/new' => 'units#new'

  scope 'users' do
      get '/relative' => 'relatives#search_relative'
    scope '/:id' do
      get '/set_photo' => 'users#set_photo'
      get '/set_profile_details' => 'users#set_profile_details'
      get '/set_medical_histories' => 'users#set_medical_histories'
      get '/set_relatives' => 'users#set_relatives'

      put '/set_profile_details' => 'users#update_profile_details'
      post '/relatives' => 'relatives#create'
      put '/sign_up_details' => 'users#sign_up_details'
      post '/upload_photo' => 'users#upload_photo'
      post '/add_allergies' => 'users#add_allergies'
    end
  end

  scope 'institutions' do
    scope ':institution_id' do
      scope 'visit_notes' do
        scope ':id' do
          get '/step_two' => 'visit_note_steps#step_two'
          get '/step_three' => 'visit_note_steps#step_three'
          get '/step_four' => 'visit_note_steps#step_four'
          get '/step_five' => 'visit_note_steps#step_five'
          get '/step_six' => 'visit_note_steps#step_six'

          post '/set_diagnosis' => 'visit_note_steps#set_diagnosis'
          post '/set_therapy' => 'visit_note_steps#set_therapy'
          post '/set_action' => 'visit_note_steps#set_action'
          post '/set_allergies' => 'visit_note_steps#set_allergies'
          post '/set_medical_treatment' => 'visit_note_steps#set_medical_treatment'
        end
      end
    end
  end

  scope 'hospitals' do
    scope ':id' do
      put '/inst_profile' => 'hospital_steps#add_inst_profile'
      put '/inst_details' => 'hospital_steps#add_inst_details'
      post '/beds' => 'hospital_beds#create'
      post '/departments' => 'departments#add_in_inst'
      post '/assign_supplier' => 'suppliers#assign'

      get '/step_two' => 'hospital_steps#step_two'
      get '/step_three' => 'hospital_steps#step_three'
      get '/step_four' => 'hospital_steps#step_four'

    end
  end


  resources :users
  resources :hospitals


end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :validatable

  after_initialize :generate_rm_number, if: :new_record?
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :institutions
  has_many :user_histories
  has_many :logins
  has_many :user_photos
  has_many :visit_notes
  has_many :prescriptions
  has_many :billings
  has_many :user_allergies
  has_many :relatives
  has_many :institutions, foreign_key: 'admin_mr', primary_key: 'rm_number'
  has_many :pharmacies, :foreign_key => :admin_mr, :primary_key => :rm_number

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def full_name
    return "#{self.salutation} #{self.first_name} #{self.middle_name} #{self.last_name}"
  end

  def active_for_authentication?
    super and !self.disabled
  end

  def generate_rm_number
    self.rm_number = loop do
      l = ('A'..'Z').to_a
      l.delete('I')
      l.delete('O')
      l.delete('L')
      lt = l.shuffle[0..2].join
      n = (0..9).to_a.shuffle[0..3].join
      rm = lt + n
      break rm unless User.exists?(rm_number: rm)
    end
  end


  def country_name
    c = ISO3166::Country[country]
    if c.present?
      c.name || c.translations[I18n.locale.to_s]
    end
  end

  def admin_mr?(inst_id)
    if Institution.where(:id => inst_id, :admin_mr => self.rm_number).exists?
      true
    else
      false
    end
  end

  def get_hospitals
    data = Institution.includes(:hospital).where(:admin_mr => self.rm_number, :inst_type => 'hospital').order(:name => :asc)
    data = data.as_json(:include => :hospital)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def after_inactive_sign_up_path_for(resource)
    set_photo_path(:id => resource)
  end


  
  private

  def sign_up_params
    # params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :salutation, :gender, :date_of_birth, :address_1, :address_2, :city, :state, :zip, :country)
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :gender, :date_of_birth, :place_of_birth, :id_type, :rm_number, :home_phone, :mobile_phone, :blood_type)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :middle_name, :salutation, :gender, :date_of_birth, :address_1, :address_2, :city, :state, :zip, :country)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    institutions_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i(set_photo
                                                set_profile_details
                                                upload_photo
                                                sign_up_details
                                                add_allergies
                                                update_profile_details
                                                set_medical_histories
                                                set_relatives)

  def index
    @users = User.where.not(id: current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def show
    @user = get_user(params[:id])
  end

  def edit
    @user = get_user(params[:id])
  end

  def update
    @user = get_user(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = get_user(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def set_profile_details
    @user = User.find_by_id(params[:id])
  end

  def set_photo
    @user = User.find_by_id(params[:id])
  end

  def set_medical_histories
    @user = User.find_by_id(params[:id])
  end

  def set_relatives
    @user = User.find_by_id(params[:id])
  end

  def upload_photo
    user = User.find_by_id(params[:id])
    if user.present?
      user.update(:photo => params[:photo])
      user.update(:photo_url => user.photo.url, :photo_thumb_url => user.photo.url(:thumb))
      render json: {:status => 0, :message => 'success'}
    else
      flash[:alert] = 'We couldn\'t find a user with the specified RM number.'
      render json: {:status => 1, :message => 'user not found'}
    end
  end

  def update_profile_details
    user = get_user(params[:id])
    if user.update(user_params)
      redirect_to set_medical_histories_path, {id: user.id}
    else
      flash[:alert] = user.error.full_messages
      render 'set_profile_details'
    end
  end

  def add_allergies
    user = get_user(params[:id])
    render json: {:status => 1, :message => 'user not found'}, :status => 400 and return if user.nil?
    if params[:allergies].present?
      JSON.parse(params[:allergies]).each do |item|
        user.user_allergies.create(:substance => item['substance'], :reaction => item['reaction'])
      end
    end
    render json: {:status => 0, :message => 'success'}, :status => 200
  end

  private

  def user_params
    params.permit(:first_name, :last_name, :middle_name, :salutation, :gender, :date_of_birth, :address_1,
                                 :address_2, :city, :state, :zip, :country, :email, :password, :desa, :kecamatan, :rt_rw, :kabupaten,
                                  :kelurahan, :provinsi, :education, :religion, :nationality, :marital_status, :occupation, :company,
                                  :full_address, :phone)
  end

  def get_user(id)
    User.find(id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% content_for :title do %>
  <title>Welcome! Dashboard | Dokterku</title>
<% end %>

<div id="sb-site">

<div id="page-wrapper">
<%= render 'partials/header' %>
<%= render 'partials/sidebar' %>
    <div id="page-content-wrapper">
        <div id="page-content">

                <div class="container">

<div id="page-title">
<h2>Users&nbsp;&nbsp;&nbsp;<%= link_to 'New User', new_user_path, class: 'btn btn-primary btn-sm' %></h2>
<p>All users registered in your database are listed below.</p>
<div id="theme-options" class="admin-options">
<a href="javascript:void(0);" class="btn btn-primary theme-switcher tooltip-button" data-placement="left" title="Color schemes and layout options">
    <i class="glyph-icon icon-linecons-cog icon-spin"></i>
</a>
<div id="theme-switcher-wrapper">
    <div class="scroll-switcher">
        <h5 class="header">Layout options</h5>
        <ul class="reset-ul">
            <li>
                <label for="boxed-layout">Boxed layout</label>
                <input type="checkbox" data-toggletarget="boxed-layout" id="boxed-layout" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-header">Fixed header</label>
                <input type="checkbox" data-toggletarget="fixed-header" id="fixed-header" class="input-switch-alt">
            </li>
            <li>
                <label for="fixed-sidebar">Fixed sidebar</label>
                <input type="checkbox" data-toggletarget="fixed-sidebar" id="fixed-sidebar" class="input-switch-alt">
            </li>
            <li>
                <label for="closed-sidebar">Closed sidebar</label>
                <input type="checkbox" data-toggletarget="closed-sidebar" id="closed-sidebar" class="input-switch-alt">
            </li>
        </ul>
        <div class="boxed-bg-wrapper hide">
            <h5 class="header">
                Boxed Page Background
                <a class="set-background-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
            </h5>
            <div class="theme-color-wrapper clearfix">
                <h5>Patterns</h5>
                <a class="tooltip-button set-background-style pattern-bg-3" data-header-bg="pattern-bg-3" title="Pattern 3" href="javascript:void(0);">Pattern 3</a>
                <a class="tooltip-button set-background-style pattern-bg-4" data-header-bg="pattern-bg-4" title="Pattern 4" href="javascript:void(0);">Pattern 4</a>
                <a class="tooltip-button set-background-style pattern-bg-5" data-header-bg="pattern-bg-5" title="Pattern 5" href="javascript:void(0);">Pattern 5</a>
                <a class="tooltip-button set-background-style pattern-bg-6" data-header-bg="pattern-bg-6" title="Pattern 6" href="javascript:void(0);">Pattern 6</a>
                <a class="tooltip-button set-background-style pattern-bg-7" data-header-bg="pattern-bg-7" title="Pattern 7" href="javascript:void(0);">Pattern 7</a>
                <a class="tooltip-button set-background-style pattern-bg-8" data-header-bg="pattern-bg-8" title="Pattern 8" href="javascript:void(0);">Pattern 8</a>
                <a class="tooltip-button set-background-style pattern-bg-9" data-header-bg="pattern-bg-9" title="Pattern 9" href="javascript:void(0);">Pattern 9</a>
                <a class="tooltip-button set-background-style pattern-bg-10" data-header-bg="pattern-bg-10" title="Pattern 10" href="javascript:void(0);">Pattern 10</a>

                <div class="clear"></div>

                <h5 class="mrg15T">Solids &amp;Images</h5>
                <a class="tooltip-button set-background-style bg-black" data-header-bg="bg-black" title="Black" href="javascript:void(0);">Black</a>
                <a class="tooltip-button set-background-style bg-gray mrg10R" data-header-bg="bg-gray" title="Gray" href="javascript:void(0);">Gray</a>

                <a class="tooltip-button set-background-style full-bg-1" data-header-bg="full-bg-1 fixed-bg" title="Image 1" href="javascript:void(0);">Image 1</a>
                <a class="tooltip-button set-background-style full-bg-2" data-header-bg="full-bg-2 fixed-bg" title="Image 2" href="javascript:void(0);">Image 2</a>
                <a class="tooltip-button set-background-style full-bg-3" data-header-bg="full-bg-3 fixed-bg" title="Image 3" href="javascript:void(0);">Image 3</a>
                <a class="tooltip-button set-background-style full-bg-4" data-header-bg="full-bg-4 fixed-bg" title="Image 4" href="javascript:void(0);">Image 4</a>
                <a class="tooltip-button set-background-style full-bg-5" data-header-bg="full-bg-5 fixed-bg" title="Image 5" href="javascript:void(0);">Image 5</a>
                <a class="tooltip-button set-background-style full-bg-6" data-header-bg="full-bg-6 fixed-bg" title="Image 6" href="javascript:void(0);">Image 6</a>

            </div>
        </div>
        <h5 class="header">
            Header Style
            <a class="set-adminheader-style" data-header-bg="bg-gradient-9" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-adminheader-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-adminheader-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-adminheader-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-adminheader-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-adminheader-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-adminheader-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-adminheader-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-adminheader-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-adminheader-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
        <h5 class="header">
            Sidebar Style
            <a class="set-sidebar-style" data-header-bg="" title="Remove all styles" href="javascript:void(0);">Clear</a>
        </h5>
        <div class="theme-color-wrapper clearfix">
            <h5>Solids</h5>
            <a class="tooltip-button set-sidebar-style bg-primary" data-header-bg="bg-primary font-inverse" title="Primary" href="javascript:void(0);">Primary</a>
            <a class="tooltip-button set-sidebar-style bg-green" data-header-bg="bg-green font-inverse" title="Green" href="javascript:void(0);">Green</a>
            <a class="tooltip-button set-sidebar-style bg-red" data-header-bg="bg-red font-inverse" title="Red" href="javascript:void(0);">Red</a>
            <a class="tooltip-button set-sidebar-style bg-blue" data-header-bg="bg-blue font-inverse" title="Blue" href="javascript:void(0);">Blue</a>
            <a class="tooltip-button set-sidebar-style bg-warning" data-header-bg="bg-warning font-inverse" title="Warning" href="javascript:void(0);">Warning</a>
            <a class="tooltip-button set-sidebar-style bg-purple" data-header-bg="bg-purple font-inverse" title="Purple" href="javascript:void(0);">Purple</a>
            <a class="tooltip-button set-sidebar-style bg-black" data-header-bg="bg-black font-inverse" title="Black" href="javascript:void(0);">Black</a>

            <div class="clear"></div>

            <h5 class="mrg15T">Gradients</h5>
            <a class="tooltip-button set-sidebar-style bg-gradient-1" data-header-bg="bg-gradient-1 font-inverse" title="Gradient 1" href="javascript:void(0);">Gradient 1</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-2" data-header-bg="bg-gradient-2 font-inverse" title="Gradient 2" href="javascript:void(0);">Gradient 2</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-3" data-header-bg="bg-gradient-3 font-inverse" title="Gradient 3" href="javascript:void(0);">Gradient 3</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-4" data-header-bg="bg-gradient-4 font-inverse" title="Gradient 4" href="javascript:void(0);">Gradient 4</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-5" data-header-bg="bg-gradient-5 font-inverse" title="Gradient 5" href="javascript:void(0);">Gradient 5</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-6" data-header-bg="bg-gradient-6 font-inverse" title="Gradient 6" href="javascript:void(0);">Gradient 6</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-7" data-header-bg="bg-gradient-7 font-inverse" title="Gradient 7" href="javascript:void(0);">Gradient 7</a>
            <a class="tooltip-button set-sidebar-style bg-gradient-8" data-header-bg="bg-gradient-8 font-inverse" title="Gradient 8" href="javascript:void(0);">Gradient 8</a>
        </div>
    </div>
</div>
</div>
</div>

<div class="row">
<div class="col-xs-12 table-responsive">
  <% if @users.any? %>
    <table class="table table-stripped" id="hospital_table">
      <thead>
        <tr>
          <th>RM Number</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Actions</td>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.rm_number %></td>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to 'Details', user_path(user), class: 'btn btn-info' %>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary' %>
              <%= link_to 'Delete', user_path(user), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info">You don't have any users right now.</div>
  <% end %>
</div>
</div>
</div>
                </div>



        </div>
    </div>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
  <title>New User | Dashboard | Dokterku</title>
<% end %>

<div id="sb-site">

<div id="page-wrapper">
    <%= render 'partials/header' %>
    <%= render 'partials/sidebar' %>
    <div id="page-content-wrapper">
        <div id="page-content">
            <div class="container">
                <div class="panel">
                    <div class="panel-body">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/users/set_medical_histories.html.erb
<div class="container mt-20">
  <% if @user.present? %>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h2 class="mrg10A">Create Your Profile</h2>
        <hr>
        <ul class="steps-flow p-0 mb-20">
          <li class="ptb-10 prl-10 done">1 About</li>
          <li id="tab-step2" class="ptb-10 prl-10 done">2 Profile picture</li>
          <li id="tab-step3" class="ptb-10 prl-10 done">3 More details</li>
          <li id="tab-step4" class="ptb-10 prl-10 done">4 Medical histories</li>
          <li id="tab-step5" class="ptb-10 prl-10">5 Family members</li>
        </ul>
        <hr>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">1 About</a></li>
          <li class="breadcrumb-item" id="tab-link2"><a href="#">2 Profile picture</a></li>
          <li class="breadcrumb-item" id="tab-link3"><a href="#">3 More details</a></li>
          <li class="breadcrumb-item" id="tab-link4"><a href="#" class="active">4 Medical histories</a></li>
        </ol>
      </div>
    </div>
    <!-- Start step 4 -->
    <div id="step4" class="row mt-20">
      <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
        <form name="step4" class="form-horizontal bordered-row mb-40">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <div class="form-group">
                <label class="col-sm-2 control-label">Substance</label>
                <div class="col-sm-10">
                  <textarea name="substance"
                    id="substance"
                    rows="3"
                    class="form-control textarea-autosize"
                    style="overflow: hidden;
                        word-wrap: break-word;
                        resize: horizontal;">
                  </textarea>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <div class="form-group">
                <label class="col-sm-2 control-label">Reaction</label>
                <div class="col-sm-10">
                  <textarea name="reaction"
                    rows="3"
                    id="reaction"
                    class="form-control textarea-autosize"
                    style="overflow: hidden;
                        word-wrap: break-word;
                        resize: horizontal;">
                  </textarea>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <%= link_to 'Skip', set_relatives_path({id: @user.id}), class: 'btn btn-default', id: 'skip-med-history'%>
              <button class="btn btn-azure" id="save-user-allergies">Save</button>
              <%= link_to 'Next', set_relatives_path({id: @user.id}), class: 'btn btn-info', style: 'display: none', id: 'go-set-rel'%>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- End step 4-->
  <% else %>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h2 class="mrg10A">User not found</h2>
        </div>
      </div>
  <% end %>
</div>

app/views/users/set_photo.html.erb
<div class="container mt-20">
  <% if @user.present? %>
    <div class="row">

      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h2 class="mrg10A">Create Your Profile</h2>
        <hr>
        <ul class="steps-flow p-0 mb-20">
          <li class="ptb-10 prl-10 done">1 About</li>
          <li id="tab-step2" class="ptb-10 prl-10 done">2 Profile picture</li>
          <li id="tab-step3" class="ptb-10 prl-10">3 More details</li>
          <li id="tab-step4" class="ptb-10 prl-10">4 Medical histories</li>
          <li id="tab-step5" class="ptb-10 prl-10">5 Family members</li>
        </ul>
        <hr>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">1 About</a></li>
          <li class="breadcrumb-item" id="tab-link2"><a href="#" class="active">2 Profile picture</a></li>
        </ol>
      </div>
    </div>
    <!-- Start step 2 -->

    <div id="step2" class="row mt-20" >
      <div class="col-lg-6 col-md-8 col-sm-10 col-sx-12">
        <div class = "panel panel-default">
          <div class = "panel-body">
            <form name="uploader-photo" class="form-upload-photo">
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-sx-12">
                  <div class="wrap-default-picture">
                    <img src="/img/default.png" alt="default picture">
                  </div>
                  <div class="caption" id="caption-photo"></div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-sx-12">
                  <div class="row text-center">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12">
                      <div id="upl-fr-pc" class="text-uppercase text-center pt-60">
                        <strong class="wrap-field action text-transform">
                          Upload photo
                          <input type="file" name="photo" id="photo" class="action">
                        </strong>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-sx-12 pt-20 text-right">
                  <%= link_to 'Skip', set_profile_details_path({id: @user.id}), class: 'btn btn-default'%>
                  <button class="btn btn-azure" id="save-photo">Save photo</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- End step 2 -->
    </div>
  <% else %>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h2 class="mrg10A">User not found</h2>
      </div>
    </div>
  <% end %>
</div>